<a href="https://colab.research.google.com/github/SonramSirirat/data-science-programming/blob/main/Quiz4_Q14_Q16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Quiz4:
1. Q14: Try this (ppt. 37)

    import numpy as np

    form scipy.linalg import solve

In [ ]:
import numpy as np
from scipy.linalg import solve
A = np.array([[1., 2.], [3., 4]])
b = np.array([1., 4.])
x = solve(A, b)
print(x)

[ 2.  -0.5]


2. Q15: Create a Matrix X4X3 (ppt. 41)

\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9\\
10 & 11 & 12
\end{bmatrix}

    1. Construst this matrix in Python using the function array. 
    what is result of the expression M[2, :]?  
    What is the result of the similar expression M[2: ]?

In [33]:
import numpy as np
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(M)
print(M[2, :]) # 3rd row [7 8 9]
print(M[2: ]) # 3rd and 4th row [7 8 9] [10 11 12]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[7 8 9]
[[ 7  8  9]
 [10 11 12]]


3. Q16: Create Matrix Aij

    Aij
    1. 0 if i < j and j! = m
    2. 1 if i = j or j = m
    3. -1 otherwise

In [79]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
